baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "norah.xyz" # the base hostname & protocol for your site.

paginate: 6 #articles per page
paginate_path: /blog/page:num #makes pagination working

# header text
title: Norah
header: making my way downtown

# for welcome page
# to replace image go to index.html
email:
  address: "div@pdx.edu"
  text: "div at pdx.edu"

# disqus comment
#disqus:
#    shortname: "Disqus test" #your disqus comment short name

# google analytics
google:
    tracking-id: "UA-56393460-1" #your tracking id here

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"

permalink: /posts/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
